### ISSUE TITLE
add cachix for ci build

### ISSUE THREAD

**Issue by dzmitry-lahoda** [andresilva/polkadot.nix#10]
composable can donate key https://app.cachix.org/organization/composablefi/cache/polkadot#pull - as long as composalbe exists, we will pay for cache

use 

https://determinate.systems/posts/magic-nix-cache for builds

or 

https://github.com/nixbuild/

for builds

so builds are fast and cached

**Comment by andresilva** [comment]
Thanks for the cache key donation. I guess I can use my own cache for the initial setup (also since this is a public cache the free tier should be enough). I'll look into the links you provided.

Also I'm sorry I'm replying slowly to your issues, this is just a hobby project for me and not my main focus, so my time here is a bit more limited.

**Comment by dzmitry-lahoda** [comment]
> Also I'm sorry I'm replying slowly to your issues, this is just a hobby project for me and not my main focus, so my time here is a bit more limited.

no worries. so you may consider "donate" repo to some org, like nix-community, paritytech if they accept it. i guess it will ease repo discovery and trust into it, so more PRs will follow. 

in case if repo donated to ComposableFi/polkadot.nix, I will be able to spend more time PRing. I need faster turnaround so, so most of things go to ComposableFe/composable repo.

**Comment by andresilva** [comment]
Done.
